<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "empadministration"
 *
 * Auto generated by Extension Builder 2020-12-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Employee Administration',
    'description' => 'An employee administration for the personnel department of a company is desired.',
    'category' => 'plugin',
    'author' => 'Jayprakash',
    'author_email' => 'jayprakash.yug@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
